define(['angular'], function (angular) {
    "use strict";

    var factory = function (localStorage) {

    var constantVal = {
	 
     // SIT Dev URL
     /* version : '3.0',
     appName : 'SIT 3',
     MainUrl : "http://rcsmobile.itcinfotech.com:3001/test/getURL", */
     
    // SIT Test URL
     version : '6.0',
     appName : 'SIT 1',
     MainUrl : "https://rcsdqssit.rcsoncloud.com:8443/getURL",
	 
	 // UAT URL
	 /* version : '4.0',
     appName : 'UAT 2',
     MainUrl : "https://rcsdqscb.rcsoncloud.com:8443/getUrl", */
	 
	
	Releasebuild:releaseBuild,
	serviceTimeout:40000,
	serviceSlowTimeout:180000,
	dqsStatusCheckTimeGap:(2 * 60 * 1000),
    loginURI: '',
    samlToken: '',
    accessToken: localStorage.getItem("access_Token"),
    expiresin: localStorage.getItem("expires_in"),
    refreshToken: localStorage.getItem("refresh_Token"),
    password: "",
    base64password: "batrcs8@123",
    shouldSyncData: false,
    isDownSyncRequired: false,
    encString: null,
    gpsEnabled : true,
    distanceConvFactor: 3280.8, 
    cnt: 0,
	outletListArr : [],
    assignmentDate: "2014-11-12T18:30:00.000+0000",
    userName: localStorage.getItem("un"),
    userFirstName: localStorage.getItem("ufn"),
    logging: localStorage.getItem("logging"),
    userTerritoryID: localStorage.getItem("tid"),
    userID: localStorage.getItem("uid"),
	syncStartTime : "",
	syncEndTime : "",
	syncType : "Incremental Sync",
    tblRCSEmployee: "RCSEmployee",
    tblRCSSalesTarget: "RCSSalesTarget",
    tblRCSCustomer: "RCSCustomer",
    tblRCSServiceRequest: "RCSServiceRequest",
    tblRCSRoute: "RCSRoute",
    tblRCSDateRoute: "RCSDateRoute",
    tblRCSCustomerRoute: "RCSCustomerRoute",
    tblRCSCustomerAddress: "RCSCustomerAddress",
    tblRCSCustomerTradingTerm: "RCSCustomerTradingTerm",
    tblRCSCustomerProductsHeader: "RCSCustomerProductsHeader",
    tblRCSCustomerProduct: "RCSCustomerProduct",
    tblRCSProduct: "RCSProduct",
    tblRCSCustomerSupplier: "RCSCustomerSupplier",
    tblRCSContact: "RCSContact",
    tblRCSPrintCommon: "RCSPrintCommon",
    tblRCSCustomerCallTime: "RCSCustomerCallTime",
    tblRCSLookup: "RCSLookup",
    tblRCSCustomerMerchandise: "RCSCustomerMerchandise",
    tblRCSMerchandise: "RCSMerchandise",
    tblRCSCustomerCallDate: "RCSCustomerCallDate",
    tblRCSCustomerActivity: "RCSCustomerActivity",
    tblRCSActivity: "RCSActivity",
    tblRCSCustomerTerritory: "RCSCustomerTerritory",
    tblRCSPricelistHeader: "RCSPricelistHeader",
    tblRCSSeasonality: "RCSSeasonality",
    tblRCSTerritoryFeatures: "RCSTerritoryFeatures",
    tblRCSCustomerContact: "RCSCustomerContact",
    tblRCSTemplate: "RCSTemplate",
    tblRCSAssessmentTemplate: "RCSAssessmentTemplate",
    tblRCSResponse: "RCSResponse",
    tblRCSCustAssesHeader: "RCSCustAssesHeader",
    tblRCSCustAssesDetail: "RCSCustAssesDetail",
    tblRCSCustContract: "RCSCustContract",
    tblRCSCustContractDriver: "RCSCustContractDriver",
    tblRCSInventoryLocation: "RCSInventoryLocation",
    tblRCSMileAge: "RCSMileAge",
    tblRCSCustomerAdhocRoute: "RCSCustomerAdhocRoute",
    tblRCSSalesOrderHeader: "RCSSalesOrderHeader",
    tblRCSSupplier: "RCSSupplier",
    tblRCSPricelistDetail: "RCSPricelistDetail",
    tblRCSSalesOrderDetail: "RCSSalesOrderDetail",
    tblRCSStockLoadHeader: "RCSStockLoadHeader",
    tblRCSStockLoadDetail: "RCSStockLoadDetail",
    tblRCSInvoiceDetail: "RCSInvoiceDetail",
    tblRCSInvoiceHeader: "RCSInvoiceHeader",
    tblRCSPayment: "RCSPayment",
    tblRCSInvoicePayment: "RCSInvoicePayment",
    tblRCSStockReconHeader: "RCSStockReconHeader",
    tblRCSStockReconDetail: "RCSStockReconDetail",
    tblRCSInventoryLevel: "RCSInventoryLevel",
    tblRCSTerritory: "RCSTerritory",
    tblRCSEmployeeGroup: "RCSEmployeeGroup",
    tblRCSMessage: "RCSMessage",
    tblRCSEmployeeMessage: "RCSEmployeeMessage",
    tblRCSGroup: "RCSGroup",
    tblRCSAccount: "RCSAccount",
    tblRCSContract: "RCSContract",
    tblRCSContractDriver: "RCSContractDriver",
    tblRCSContComplianceHdr: "RCSContComplianceHdr",
    tblRCSContComplianceDetl: "RCSContComplianceDetl",
    tblRCSVROHeader: "RCSVROHeader",
    tblRCSVRODetail: "RCSVRODetail",
	tblRCSRetailAuditLOV: "RCSRetailAuditLOV",
	tblRCSAddOutletLOV: "RCSAddOutletLOV",
	tblRCSAddressLOV: "RCSAddressLOV",
	tblRCSContactLOV: "RCSContactLOV",
	tblRCSAssessmentLOV: "RCSAssessmentLOV",
	tblRCSOutletTimeLOV: "RCSOutletTimeLOV",
	tblRCSEditOutletLOV: "RCSEditOutletLOV",
	tblRCSServiceRequestLOV: "RCSServiceRequestLOV",
	tblRCSMerchandisingLOV : "RCSMerchandisingLOV",
	tblRCSMobileConfigLOV : "RCSMobileConfigLOV",
	tblRCSReturnOrderLOV : "RCSReturnOrderLOV",
	tblRCSActivityLOV: "RCSActivityLOV",
    tblRCSPaymentLOV: "RCSPaymentLOV",
    tblRCSContractLOV: "RCSContractLOV",
	tblRCSProfileLOV : "RCSProfileLOV",
	tblRCSEndMyDayLOV : "RCSEndMyDayLOV",
	tblRCSBatConfigLOV : "RCSBatConfigLOV",
	tblRCSCountryLOV : "RCSCountryLOV",
	tblRCSCityLOV : "RCSCityLOV",
	tblRCSStateLOV : "RCSStateLOV",
	tblRCSSuburbLOV : "RCSSuburbLOV",
	tblRCSCustomerNote : "RCSCustomerNote",
	tblRCSSyncReport  : "RCSSyncReport",
	tblRCSSOQFeatures  : "RCSSOQFeatures",
	tblRCSCustomerSalesTarget : "RCSCustomerSalesTarget",
	tblRCSRecentVisitOrderInfo : "RCSRecentVisitOrderInfo",
	tblRCSRecentVisitROXOInfo : "RCSRecentVisitROXOInfo",
	tblRCSRecentVisitStockCountInfo : "RCSRecentVisitStockCountInfo",
	tblRCSBundleDetail : 'RCSBundleDetail',
	tblRCSAppSetting : 'RCSAppSetting',
	tblRCSStockTransferHeader: 'RCSStockTransferHeader',
	tblRCSStockTransferDetail: 'RCSStockTransferDetail',
	tblRCSDistributor : 'RCSDistributor',
	tblRCSMobileModulePrivs : 'RCSMobileModulePrivs',
	tblRCSCalendarPlannerHeader : 'RCSCalendarPlannerHeader',
	tblRCSCalendarPlannerDetail : 'RCSCalendarPlannerDetail',
	tblRCSDiscountPlan : 'RCSDiscountPlan',
	tblRCSDiscountRule : 'RCSDiscountRule',
	tblRCSAssortmentHeader : 'RCSAssortmentHeader',
	tblRCSAssortmentDetail : 'RCSAssortmentDetail',
	tblRCSCustomerDiscountRuleUtilization : 'RCSCustomerDiscountRuleUtilization',
	tblRCSPricingBCPLOV : 'RCSPricingBCPLOV',
	tblRCSInventoryTXN : 'RCSInventoryTXN',
    tblRCSDeleteTracker : 'RCSDeleteTracker',
	tblRCSTradePayment : 'RCSTradePayment',
	tblRCSRetailAuditGroup : 'RCSRetailAuditGroup',
	tbRCSRetailAuditSetting : 'RCSRetailAuditSetting',
    colRCSCustomerID: "rcsCustomerID",
    colRCSCustomerName: "rcsCustomerName",
    colRCSPricelistID: "rcs_Pricelist_ID",
    colWithhold_tax: "withhold_tax",
    colavailableCredit: "available_Credit",
	  colCreditLimit: "credit_Limit",
    colCreditDays: "available_CreditDays",
    colAuthorityTemplateID: "authorityTemplateID",
    colVolumeTemplateID: "volumeTemplateID",
    colShopperChannelTemplateID: "shopperChannelTemplateID",
    colCommunicationTemplateID: "communicationTemplateID",
    colASUTemplateID: "asuTemplateID",
    coldiscount: "discount",
    colTradingDays: "tradingDays",
	colTci_Bonus_Bucket : "tci_Bonus_Bucket",
	colTci_Dis_Bucket : "tci_Dis_Bucket",
	colPaymentMehod : "paymentMehod",
    varRcsCustomerIDForAddInfo: "D3F28467-0C64-E411-B51C-005056B57717",
    varRcsCustomerIDForStockAudit: "24F78467-0C64-E411-B51C-005056B57717",
	delivLeadTime: "delivLeadTime",

    outletShippAddCopyFrmPrim: false,
    outletBillAddCopyFrmPrim: false,
    addreessBillCheck: false,
    addreessShipCheck: false,
    assesmentAuthorityTemplateIDArray: [],
    promptSalesHeaderID: "",
    salesOrderLoop: 0,
    iventoryLevelJson: [],
    skuLineNo: 0,
    tblCount: 0,
    downloadComplete: 0,
    errorTblCount: 0,
    salesOrderDisplyList: 0,
    salesListArray: [],
    noCallFlag: false,
    modificationChange: true,
    primaryContactID: "",
    volumeResult: '',
    communicationResult: '',
    authorityResult: '',
    shopperChannelResult: '',
	salesContractArr : [],
	salesComplianceArr : '',
	salesContractArrPosition : 0,
	salesComplianceArrPosition : 0,
	salesComplianceArrLength : 0,
	fullIventoryLevelJson : '',
	resCustId : '',
	gpsIgnoreFlag : '',
	addDeleteFlag : 0,
	firstLogin: false,
	contractTypeHash : "contractTypeHash",
	chkFreqHash : "chkFreqHash",
	compNameHash : "compNameHash",
	driverHash : "driverHash",
    categoryIdHash : "categoryIdHash",
    compensationTypeHash : "compensationTypeHash",
    driverList : "driverList",
    zambia: "Zambia",
    BTW : "BWA",
    lesotho : "LSO",
			MMR : "MMR",
			UGA: "UGA"


};

var en_message = {
		checkInternet : "Internet connection is not available/Server is down,please try again later",
		noCalls: "No calls available for the selected Date",
		noData : "Sorry, no Data to display.",
		inventoryLocationEmpty : "We could not find inventory location for you. Please contact administator.",
		syncSuccess :"Sync Success!",
		syncUploadFailed :"Sync Upload Failed! Please try again",
		PendingForProcess : "Data upload processing is still in progress, Please retry after sometime",
		NetworkUnavailable : "Network Unavailable",
		upsyncCompleted : "Upload Sync Completed",
		tryReDownloading : "tables has failed to Download. Please try Re downloading",
		noInternet : "Please check your internet connection",
		problemAuth : "Problem during Authentication",
		ServerDown:"Currently the server is unavailable,please try after sometime",
		incorrectUsernamePassword:"Username/password incorrect",
		usernamePasswordMsg :"Please enter Username and Password",
		invalidPassword : "Username or Password does not match. Please contact administrator.",
 };


var vn_message = {
	checkInternet : "Hiện không có kết nối Internet, hoặc máy chủ không kết nối. Hãy thử lại sau 5 phút nữa.",
	noCalls: "Không có điểm bán nào vào ngày hôm nay.",
	noData : "Không có dữ liệu để hiển thị.",
	inventoryLocationEmpty: "Hệ thống không có mã kho của bạn. Hãy liên hệ đội hỗ trợ.",
	syncSuccess: "Đồng bộ thành công!",
    syncUploadFailed: "Có lỗi khi đồng bộ. Hãy thử lại sau 5 phút",
    PendingForProcess : "Đang gửi dữ liệu về máy chủ. Hãy thử lại sau 10 phút nữa",
	NetworkUnavailable : "Không có kết nối mạng. Thử lại sau 5 phút nữa.",
	upsyncCompleted : "Đồng bộ 1 phần thành công",
	tryReDownloading : "1 phần dữ liệu chưa được tải về. Thử Đồng bộ toàn phần sau 5 phút.",
	noInternet : "Kiểm tra kết nối Internet và thử lại sau 5 phút.",
	problemAuth : "Lỗi xác thực người dung.",
	ServerDown:"Máy chủ đang bị lỗi. Thử lại sau 30 phút nữa.",
	incorrectUsernamePassword:"Tên người dùng / mật khẩu không đúng.",
	usernamePasswordMsg :"Hãy nhập tên người dùng và mật khẩu.",
	invalidPassword : "Tên người dùng và mật khẩu không khớp. Liên hệ nhân  viên L1.",
};



var hk_message = {
	checkInternet : "沒有可用網絡或伺服器繁忙，請稍後再試",
	noCalls: "所選擇的日期，沒有可探訪提供。",
	noData : "沒有資料可顯示",
	inventoryLocationEmpty : "我們為你找不到倉存位置。請與管理員聯繫",
	syncSuccess :"同步成功",
	syncUploadFailed :"同步上傳失敗！請再試一次",
	PendingForProcess : "資料上載中, 請稍侯再試",
	NetworkUnavailable : "網絡未連接",
	upsyncCompleted : "上傳完成",
	tryReDownloading : "資料下載失敗， 請嘗試重新下載。",
	noInternet : "Please check your internet connection",
	problemAuth : "Problem during Authentication",
	ServerDown:"Currently the server is unavailable,please try after sometime",
	incorrectUsernamePassword:"使用者名稱/密碼不正確",
	usernamePasswordMsg :"請輸入使用者名稱及密碼",
    invalidPassword : "使用者名稱/密碼",
};


var angola_message = {
	checkInternet :"Tente mais tarde, internet/servidor fora de serviço",
	noCalls:"Visitas indisponiveis para as datas seleccionadas",
	noData :"Desculpe! Não há informação para exibir",
	inventoryLocationEmpty :"Não conseguimos encontrar o inventário. Por favor contacte o Administrador.",
	syncSuccess :"Sincr. com sucesso",
	syncUploadFailed :"Falha na Sincr.! Tente de novo",
	tryReDownloading:"Erros de descarga. Tente novamente.",
	upsyncCompleted:"Sinc. de Envio COMPLETA",
	PendingForProcess : "O envio de informação continua em andamento, tente mais tarde.",
	NetworkUnavailable:"Rede Indisponivel",
	noInternet : "Por favor verifique a conexão a internet.",
	problemAuth : "Problemas durante Autenticação",
	ServerDown:"O Servidor encontra-se indisponivel, tente mais tarde.",
	incorrectUsernamePassword:"nome do usuário/senha incorrecta",
	usernamePasswordMsg :"Por favor insira o nome do usuário e a senha",
	invalidPassword : "Nome de Usuario e/ou Palavra chave errada. Por favor contacte o Administrador",
};

var urdu_message = {
	checkInternet : "انٹرنیٹ کنکشن میسر نہیں ۔ برائے مہربانی کچھ دیر بعد کوشش کریں۔",
	noCalls: "مطلوبہ تاریخ کے لیے کوئی کال دستیاب نہیں",
	noData : "معذرت! ڈسپلے کے لیے کوئی ڈیٹا نہیں ہے ۔",
	inventoryLocationEmpty : "آپ کی انونٹری لوکیشن معلوم نہیں ہو سکتی۔ برائے مہربانی ایڈمنسٹریٹر سے رابطہ کریں ۔ ",
	syncSuccess :"Sync کامیابی سے ہو گیا ہے",
	syncUploadFailed :"Sync اپ لوڈ نا کام ! برائے مہربانی دوبارہ کو شش کریں",
	PendingForProcess : "ڈیٹا اپ لوڈ کرنے کا عمل ابھی بھی جاری ہے ، برائے مہربانی تھوڑی دیر بعد دوبارہ کوشش کریں ",
	NetworkUnavailable : "نیٹ ورک دستیاب نہیں",
	upsyncCompleted : "اپ لوڈ Sync مکمل ہو گیا ہے",
	tryReDownloading : "ٹیبل ڈاون لوڈ ہونے میں نا کام ہوا ہے ۔ برائے مہربانی دوبارہ ڈاون لوڈنگ کی کو شش کریں ۔ ",
	noInternet : "برائے مہربانی اپنا انٹرنیٹ کنکشن چیک کریں ",
	problemAuth : "تصدیق میں مسٗلہ",
	ServerDown:"فل وقت سرور دستیاب نہیں برائے مہربانی کچھ دیر بعد کو شش کیجئے ۔",
	incorrectUsernamePassword:"صارف کا نام / پاس ورڈ غلط ہے",
	usernamePasswordMsg :" برائے مہربانی صارف کا نام اور پاس ورڈ درج کریں",
    invalidPassword : "صارف کا نام یا پاس ورڈ غلط ہے. برائے مہربانی منتظم سے رابطہ کریں",
};
	var  russian_msg ={
	checkInternet: "Нет доступа к Интернету. Попробуйте позже",
	noCalls:"Нет визитов на выбранную дату",
	noData: "Нет данных",
	inventoryLocationEmpty: "Невозможно найти остатки. Обратитесь к администратору",
	syncSuccess: "Синхронизация прошла успешно",
	syncUploadFailed: "Синхронизация провалена. Попробуйте еще раз",
	tryReDownloading:"Загрузка провалена. Попробуйте еще раз",
	upsyncCompleted:"Синхронизация UPLOAD завершена",
	NetworkUnavailable:"Связь не доступна",
	noInternet:"Проверье подключениек Интернету",
	problemAuth:"Провблема с аутентификацией",
	ServerDown:"Сервер не доступен. Попробуйте позже",
	PendingForProcess:"Загрузка в процессе. Попробуйте позже",
	incorrectUsernamePassword:"Имя пользователя/пароль некорректны",
	usernamePasswordMsg :"Введите имя пользователя и пароль",
	invalidPassword : "Имя пользователя или пароль не совпадают. Пожалуйста, обратитесь к администратору.",
};

var lru_msg ={
	checkInternet: "Connection internet indisponible/Serveur en panne. Réessayez plus tard",
	noCalls:"Aucune visite disponible à la date sélectionnée",
	noData: "Désolé ! Aucune donnée affichée",
	inventoryLocationEmpty: "Nous n'avons pas pu localiser un inventaire pour vous. Merci de contacter l'administrateur",
	syncSuccess: "Synchronisation réussie !",
	syncUploadFailed: "Echec du téléchargement Sync. Veuillez ré-essayer",
	tryReDownloading:"Le téléchargement des tableaux a échoué. Veuillez réessayer", 
	upsyncCompleted:"Upload reussi",
	NetworkUnavailable:"Réseau indisponible",
	noInternet:"Merci de vérifier votre connexion internet",
	problemAuth:"Un problème est survenu pendant l'authentification",
	ServerDown:"Le serveur est actuellement indisponible. Veuillez réessayer plus tard",
	PendingForProcess:"Le processus de téléchargement des données est toujours en cours. Veuillez réessayer plus tard",
	incorrectUsernamePassword:"Username/password incorrect",
	usernamePasswordMsg :"Veuillez entrer votre nom d'utilisateur et mot de passe.",
	invalidPassword : "Nom d'utilisateur ou Mot de passe incorrect. Veuillez contacter votre administrateur.",
};
var algeria_msg ={
	checkInternet: "Connection internet indisponible/Serveur en panne. Réessayez plus tard",
	noCalls:"Aucune visite disponible à la date sélectionnée",
	noData: "Désolé ! Aucune donnée affichée",
	inventoryLocationEmpty: "Nous n'avons pas pu localiser un inventaire pour vous. Merci de contacter l'administrateur",
	syncSuccess: "Synchronisation réussie !",
	syncUploadFailed: "Echec du téléchargement Sync. Veuillez ré-essayer",
	tryReDownloading:"Le téléchargement des tableaux a échoué. Veuillez réessayer", 
	upsyncCompleted:"Upload reussi",
	NetworkUnavailable:"Réseau indisponible",
	noInternet:"Merci de vérifier votre connexion internet",
	problemAuth:"Un problème est survenu pendant l'authentification",
	ServerDown:"Le serveur est actuellement indisponible. Veuillez réessayer plus tard",
	PendingForProcess:"Le processus de téléchargement des données est toujours en cours. Veuillez réessayer plus tard",
	incorrectUsernamePassword:"Nom d'utilisateur / Mot de Passe est incorrecte ",
	usernamePasswordMsg :"Merci d'entrer le Nom d'utilisateur et le Mot de Passe",
	invalidPassword : "Le Nom d'utilisateur ou le Mot de passe est incorrect. Veuillez contacter votre administrateur.",
};
		
var french_message = {
		checkInternet : "Connection internet indisponible/Serveur en panne. Réessayez plus tard",
		noCalls: "Aucune visite disponible à la date sélectionnée",
		noData : "Désolé ! Aucune donnée affichée",
		inventoryLocationEmpty : "Nous n'avons pas pu localiser un inventaire pour vous. Merci de contacter l'administrateur",
		syncSuccess :"Synchronisation réussie !",
		syncUploadFailed :"Echec du téléchargement Sync. Veuillez ré-essayer",
		PendingForProcess : "Le processus de téléchargement des données est toujours en cours. Veuillez réessayer plus tard",
		NetworkUnavailable : "Réseau indisponible",
		upsyncCompleted : "Téléchargement sync achevé",
		tryReDownloading : "Le téléchargement des tableaux a échoué. Veuillez réessayer ",
		noInternet : "Merci de vérifier votre connexion internet",
		problemAuth : "Un problème est survenu pendant l'authentification",
		ServerDown:"Le serveur est actuellement indisponible. Veuillez réessayer plus tard",
		incorrectUsernamePassword:"Nom d'utilisateur/mot de passe invalide",
		usernamePasswordMsg :"Veuillez entrer un nom d'utilisateur et un mot de passe",
		invalidPassword : "Le nom d'utilisateur ou le mot de passe n'est pas le bon. Contactez l'administrateur",
 };
		
var tablesToDownloade = [
			"RCSEmployee",
            "RCSCustomer",
            "RCSCustomerRoute",
            "RCSDateRoute",
            "RCSCustomerAddress",
            "RCSCustomerContact",
            "RCSContact",
            "RCSCustomerTradingTerm",
            "RCSCustomerTerritory",
			"RCSProduct",
			"RCSSalesTarget",
            "RCSServiceRequest",
			"RCSCustomerCallTime",
            "RCSCustomerProductsHeader",
			"RCSCustomerProduct",
            "RCSCustomerSupplier",
            "RCSCustomerMerchandise",
            "RCSMerchandise",
            "RCSCustomerCallDate",
			"RCSCustomerActivity",
			"RCSActivity",
            "RCSRoute",
            "RCSPrintInvoiceHeader",
            "RCSPricelistHeader",
            "RCSPricelistDetail",
            "RCSTerritoryFeatures",
            "RCSSeasonality",
            "RCSTemplate",
            "RCSAssessmentTemplate",
			"RCSCustAssesHeader",
            "RCSResponse",
            "RCSCustAssesDetail",
            "RCSContract",
            "RCSInventoryLocation",
            "RCSMileAge",
            "RCSContractDriver",
            "RCSCustContract",
            "RCSCustContractDriver",
            "RCSContComplianceHdr",
            "RCSContComplianceDetl",
            "RCSCustomerAdhocRoute",
            "RCSSupplier",
            "RCSSalesOrderHeader",
            "RCSSalesOrderDetail",
            "RCSStockLoadHeader",
            "RCSStockLoadDetail",
            "RCSInvoiceDetail",
            "RCSInvoiceHeader",
            "RCSPayment",
            "RCSInvoicePayment",
            "RCSInventoryLevel",
            "RCSStockReconHeader",
            "RCSStockReconDetail",
            "RCSTerritory",
            "RCSEmployeeGroup",
            "RCSMessage",
            "RCSEmployeeMessage",
            "RCSGroup",
            "RCSAccount",
			"RCSPrintingTableDetail",
			"RCSPrintingMain",
			"RCSPrintCommon",
			"RCSProfileLOV",
			"RCSEndMyDayLOV",
			"RCSAssessmentLOV",
			"RCSOutletTimeLOV",
			"RCSContactLOV",
			"RCSEditOutletLOV",
			"RCSAddOutletLOV",
			"RCSPaymentLOV",
			"RCSContractLOV",
			"RCSReturnOrderLOV",
			"RCSMerchandisingLOV",
			"RCSMobileConfigLOV",
			"RCSServiceRequestLOV",
			"RCSActivityLOV",
			"RCSBatConfigLOV",
			"RCSCountryLOV",
			"RCSCityLOV",
			"RCSStateLOV",
			"RCSSuburbLOV",
			"RCSVROHeader",
			"RCSRetailAuditLOV",
			"RCSVRODetail",
			"RCSSOQFeatures",
			"RCSCustomerSalesTarget",
			"RCSRecentVisitOrderInfo",
			"RCSRecentVisitROXOInfo",
			"RCSRecentVisitStockCountInfo",
			"RCSBundleDetail",
			"RCSAppSetting",
			"RCSStockTransferHeader",
			"RCSStockTransferDetail",
			"RCSDistributor",
			"RCSMobileModulePrivs",
			"RCSCalendarPlannerHeader",
			"RCSCalendarPlannerDetail",
			"RCSDiscountPlan",
			"RCSDiscountRule",
			"RCSAssortmentHeader",
			"RCSAssortmentDetail",
			"RCSCustomerDiscountRuleUtilization",
			"RCSPricingBCPLOV",
            "RCSInventoryTXN",
            "RCSCustomerNote",
			"RCSTradePayment",
			"RCSRetailAuditGroup",
			"RCSRetailAuditSetting"
]

var tablePriority = {
  RCSActivity: 1,
  RCSAppSetting: 1,
  RCSAssessmentTemplate: 2,
  RCSCommonResponse: 2,
  RCSContact: 1,
  RCSContComplianceDetl: 5,
  RCSContComplianceHdr: 4,
  RCSContract: 1,
  RCSContractDriver: 2,
  RCSCustAssesDetail: 4,
  RCSCustAssesHeader: 3,
  RCSCustAssesResult: 4,
  RCSCustContract: 3,
  RCSCustContractDriver: 4,
  RCSCustomer: 2,
  RCSCustomerActivity: 3,
  RCSCustomerAddress: 3,
  RCSCustomerAdhocRoute: 3,
  RCSCustomerAttachment: 3,
  RCSCustomerCallDate: 3,
  RCSCustomerCallTime: 3,
  RCSCustomerContact: 3,
  RCSCustomerMerchandise: 3,
  RCSCustomerNote: 3,
  RCSCustomerProduct: 4,
  RCSCustomerProductsHeader: 3,
  RCSCustomerRoute: 3,
  RCSCustomerSupplier: 3,
  RCSCustomerTerritory: 3,
  RCSCustomerTradingTerm: 3,
  RCSDateRoute: 2,
  RCSDistributor: 1,
  RCSEmployee: 2,
  RCSEmployeeGroup: 3,
  RCSGroup: 1,
  RCSInventoryLevel: 4,
  RCSInventoryLocation: 3,
  RCSInventoryRecon: 4,
  RCSInventoryTXN: 4,
  RCSInvoiceDetail: 5,
  RCSInvoiceHeader: 4,
  RCSInvoicePayment: 5,
  RCSLookup: 2,
  RCSLookupSet: 1,
  RCSMerchandise: 1,
  RCSMessage: 2,
  RCSMileAge: 4,
  RCSObjectiveActivity: 1,
  RCSPayment: 3,
  RCSPricelistDetail: 2,
  RCSPricelistHeader: 1,
  RCSPrintInvoiceHeader: 1,
  RCSStagingTable: 1,
  RCSProduct: 1,
  RCSResponse: 3,
  RCSRoute: 1,
  RCSSalesOrderDetail: 4,
  RCSSalesOrderHeader: 3,
  RCSSalesTarget: 3,
  RCSSeasonality: 1,
  RCSServiceRequest: 3,
  RCSServiceRequestNote: 4,
  RCSStockLoadDetail: 5,
  RCSStockLoadHeader: 4,
  RCSStockReconDetail: 5,
  RCSStockReconHeader: 4,
  RCSStockTransferDetail: 5,
  RCSStockTransferHeader: 4,
  RCSTag: 1,
  RCSTemplate: 1,
  RCSTerritory: 1,
  RCSTranslationDetail: 2,
  RCSTranslationHeader: 1,
  RCSWeek: 1,
  RCSEmployeeMessage: 3,
  RCSSupplier: 2
}
        return {
             constantVal: function () {
                return constantVal;
            },
			vn_message : function(){
			    return vn_message;
			},
			hk_message : function(){
			    return hk_message;
			},
			angola_message :  function(){
			    return angola_message;
			},
			urdu_message :  function(){
			    return urdu_message;
			},
            tablesToDownloade: function () {
                return tablesToDownloade;
            },
			en_message: function(){
			   return en_message;
			},lru_msg: function(){
			   return lru_msg;
			},algeria_msg: function(){
			   return algeria_msg;
			},russian_msg: function(){
			   return russian_msg;
			},
			french_message: function(){
			   return french_message;
			},
			tablePriority: tablePriority			
        };

    };

    factory.$inject = ['localStorage'];
    return factory;
});